### ISSUE TITLE
[Rule Assistant] German - English crash

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#662]
This is using the projects in this folder:
https://drive.google.com/drive/folders/1uAk5R_gdPAohjYehZiEEsyJbaDtddIS3

This is the crash output:
  File "C:\Data\FLExTrans\Dev\Test Projects\FlexTools\Modules\FlexTrans\Lib\CreateApertiumRules.py", line 940, in CreateRules
    generator.ProcessAssistantFile(ruleAssistantFile, ruleNumber)
  File "C:\Data\FLExTrans\Dev\Test Projects\FlexTools\Modules\FlexTrans\Lib\CreateApertiumRules.py", line 892, in ProcessAssistantFile
    if self.ProcessRule(rule):
       ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Data\FLExTrans\Dev\Test Projects\FlexTools\Modules\FlexTrans\Lib\CreateApertiumRules.py", line 732, in ProcessRule
    apos, isAffix, default = pos, False, None, False
    ^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 3)

**Comment by rmlockwood** [comment]
The crash is fixed, but All I am getting right now is two let statements in the macro.

**Comment by mr-martian** [comment]
For some reason all the `<Feature/>` tags in the rule file had `match="" value="α"` instead of the reverse. After fixing that, I get reasonable looking output for the determiner lemma for the `"def n"` rule.

The noun suffix macro first tries number (rank 1) and finds 5 suffixes for plural and none for singular. None of these are marked for case, so it can't continue the conditional. I'm also a little confused as to what you intended the ranking in this rule to mean.

**Comment by AndyBlack** [comment]
That bug was fixed in version 0.15.1 of the GUI UI.  The latest version is 0.17.0. See https://drive.google.com/file/d/1b26zCaBk9zg_ODYxV1k2AmP66me8h6do/view?usp=drive_link

**Comment by rmlockwood** [comment]
For adjective suffixes, I don't get an otherwise block that will put out the expected ADJ.AGR for the unmarked nominative case (all genders). Below is what I get.
![image](https://github.com/user-attachments/assets/b4cd7ccc-be3a-488a-9d4e-3a113c7dda2c)

**Comment by mr-martian** [comment]
The problem here is that `ADJ_AGR` is not marked for any of the 3 features being used in this rule, so it isn't found in the process of collecting possible affixes.

**Comment by rmlockwood** [comment]
I decided I needed the 2nd (case) suffix to agree with the number of the noun. So I added number to the list of features for the 2nd suffix and my diagram looks like this:
![image](https://github.com/user-attachments/assets/23779267-d2b7-4c16-b239-5a19577bb5d2)
But now instead of getting a plain old clip for the number slot like I expected, a variable is being used.

Also, I'm still not getting the expected blank affix when the case is nominative. Nominative is the unmarked case.

**Comment by mr-martian** [comment]
Now we have the problem that when we try to enumerate number suffixes, `PL`, `ACC_PL`, `DAT_PL`, `GEN_PL`, and `NOM_PL` are all plural suffixes and `ACC_SG`, `DAT_SG`, `GEN_F_SG`, `GEN_M_SG`, and `GEN_N_SG` are all singular suffixes, so how is the macro for either affix supposed to know which of those to use and which of those are actually for the other affix?

**Comment by rmlockwood** [comment]
Case agreement is only mentioned on the 2nd suffix, so suffixes with case should go there. Also, case isn't mentioned anywhere else, so we know it originates from the source. Also it's not a feature on the word itself.
One of the number-marked suffixes above has no case, so it is only relevant for the first suffix. Number is the only feature on the first suffix and it isn't marked on the noun itself, so we know it comes from the source word. If it's important there's the implication that the number on the first suffix is primary since it has no other features and the 2nd suffix's number needs to agree with the first one.
Does this information help sort it out?

**Comment by rmlockwood** [comment]
ok. This is getting complicated so I think we will bail on the analysis where you have two affixes that both have the same feature involved in agreement. This may happen in real languages, but until we see it, let's not change the code. In this case with German, I think we can analyze the noun has having 1 suffix that is a combination of number case and gender.

**Comment by rmlockwood** [comment]
Project files updated with the new analysis.

**Comment by rmlockwood** [comment]
There's still the problem that the nominative case for the noun suffix should default to blank.

**Comment by rmlockwood** [comment]
For the adj suffix I'm not getting what I expect for the nominative singular. I expect to get ADJ.AGR. It's marked in the German lexicon as having just case:nom. So for all genders it should be this. Here's what my rule is coming out as:
![image](https://github.com/user-attachments/assets/b7631693-da94-405e-9101-61db49015357)
I didn't expect to see a choose statement on gender for nominative case.

**Comment by mr-martian** [comment]
> The problem here is that `ADJ_AGR` is not marked for any of the 3 features being used in this rule, so it isn't found in the process of collecting possible affixes.

It's this problem again. If I tag `ADJ_AGR` as nominative rather than unmarked the output is what you expect.

**Comment by mr-martian** [comment]
I updated the German project and it's still working on my end. Do we have the same RA file?

**Comment by rmlockwood** [comment]
I uploaded my files again. It looked like the same RA file, but try the one I uploaded. There’s just one rule.

**Comment by mr-martian** [comment]
It looks like this commit is to blame: https://github.com/rmlockwood/FLExTrans/commit/acd1c8273b6494e3b5d2c1710ebcb2a9c8513510

**Comment by rmlockwood** [comment]
working in latest RA build
